# application-test.yml
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

# Thêm các cấu hình khác nếu cần thiết
